[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"
authors = ["Pedro Luz <pedromsluz@gmail.com>"]

[dependencies]
reqwest = {version = "0.11.26", features = ["blocking", "json"] }
error-chain = "0.12.4"
tokio = { version = "1.36.0", features = ["full"] }
